#!/usr/bin/env bash

#        _      _____ _  #
#  _ __ (_)_  _|___ /| | #
# | '_ \| \ \/ / |_ \| | #
# | | | | |>  < ___) | | #
# |_| |_|_/_/\_\____/|_| #
#                        #

# ------------------- #
# HERBSTLUFTWM CONFIG #
# ------------------- #

# START IMPORTANT PROCESSES #
pkill polybar
pkill sxhkd
nitrogen --restore &
picom --experimental-backends &
polybar gruvbox &
dunst -config ~/.config/dunst/dunstrc &
xset r rate 200 40
xset s 0 -dpms # screensaver off
xrandr --output eDP-1 --brightness 0.8
pulseaudio --daemonize=true
# ------------------------- #

hc() {
    herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#00FF7D'
hc keyunbind --all

Mod=Mod4

hc keybind $Mod-Shift-q quit
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

sxhkd & # hotkey daemon

# TAGS #

tag_names=( {1..4} )
tag_keys=( {1..4} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# THEME #

BLACK="#282828"
GREEN="#689d6a"
BLUE="#458588" 
CYAN="#83a598" 
WHITE="#ebdbb2"
GRAY="#928374"

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $BLUE
hc set frame_border_normal_color $BLUE
hc set frame_bg_normal_color $BLUE
hc set frame_bg_active_color $BLUE
hc set frame_border_width 2
hc set always_show_frame on 
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.title_height 0
hc attr theme.title_font 'JetBrains Mono:pixelsize=12:antialias=true:autohint=true'
hc attr theme.padding_top 0 
hc attr theme.active.color $BLACK
hc attr theme.title_color $WHITE
hc attr theme.normal.color $WHITE
hc attr theme.urgent.color $BLACK
hc attr theme.normal.title_color $WHITE
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $WHITE
hc attr theme.urgent.inner_color $CYAN
hc attr theme.normal.inner_color $GREEN
hc attr theme.active.outer_width 2
hc attr theme.background_color $BLACK

hc set window_gap 7
hc set frame_padding 4
hc set smart_window_surroundings off 
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc unlock

panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    "$panel" "$monitor" &
done
