#! /bin/sh

# start hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

pkill polybar
polybar main &

bspc monitor -d "  " "  " "  " "  "

bspc config border_width 2
bspc config window_gap 12

bspc config normal_border_color "#282828"
bspc config focused_border_color "#7c6f64"

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
