#!/usr/bin/env bash

#        _      _____ _  #
#  _ __ (_)_  _|___ /| | #
# | '_ \| \ \/ / |_ \| | #
# | | | | |>  < ___) | | #
# |_| |_|_/_/\_\____/|_| #
#                        #

# ------------------- #
# HERBSTLUFTWM CONFIG #
# ------------------- #

# START IMPORTANT PROCESSES #
pkill polybar
pulseaudio --start &
nitrogen --restore &
picom --experimental-backends &
polybar main &
xset r rate 200 40 &
xrandr --output eDP-1 --brightness 0.8
# ------------------------- #

hc() {
    herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#00FF7D'
hc keyunbind --all

Mod=Mod4

# hc keybind $Mod-r spawn $HOME/.config/rofi/launchers/colorful/launcher.sh
hc keybind $Mod-r spawn rofi -show drun
hc keybind $Mod-Tab spawn rofi -show window

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close
hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}"

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode

resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

tag_names=( {1..4} )
tag_keys=( {1..4} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-e remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus #
hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         cycle_all +1
#hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme #

BLACK="#1A1826"
GREEN="#ABE9B3"
BLUE="#89DCEB" 
CYAN="#B5E8E0" 
WHITE="#D9E0EE"
GRAY="#C3BAC6"

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $BLUE
hc set frame_border_normal_color $BLUE
hc set frame_bg_normal_color $BLUE
hc set frame_bg_active_color $BLUE
hc set frame_border_width 2
hc set always_show_frame on 
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.title_height 0
hc attr theme.title_font 'Ubuntu Mono:pixelsize=12:antialias=true:autohint=true'
hc attr theme.padding_top 0 
hc attr theme.active.color $BLACK
hc attr theme.title_color $WHITE 
hc attr theme.normal.color $WHITE
hc attr theme.urgent.color $BLACK
hc attr theme.normal.title_color $WHITE
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $WHITE
hc attr theme.urgent.inner_color $BLUE
hc attr theme.normal.inner_color $GRAY
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 2
hc attr theme.background_color $BLACK

hc set window_gap 7
hc set frame_padding 4
hc set smart_window_surroundings off 
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc unlock

panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    "$panel" "$monitor" &
done
